#!/usr/bin/env python3
"""Generate Shopify products CSV for LUXE Global luxury catalog (12 items)."""
import csv

UNSPLASH_PARAMS = "?w=1200&q=80&auto=format&fit=crop"

PRODUCTS = [
    {
        "handle": "linen-tshirt",
        "title": "Organic Linen Tee",
        "body_en": "Breathable, sustainably sourced linen for everyday comfort. Pre-washed for a relaxed drape that softens with each wear.",
        "vendor": "LUXE Global",
        "category": "Apparel & Accessories > Clothing > Shirts & Tops",
        "type": "Apparel",
        "tags": "Apparel, Linen, Sustainable, Tee",
        "sku": "LXG-APP-001",
        "grams": 200,
        "qty": 50,
        "price": 4800,
        "requires_shipping": "TRUE",
        "image": "photo-1648483098902-7af8f711498f",
        "alt": "White organic linen t-shirt flat lay",
    },
    {
        "handle": "wool-jacket",
        "title": "Heritage Wool Jacket",
        "body_en": "A timeless silhouette in heavyweight Italian wool. Lined for warmth, finished by hand, built to outlast the trend cycle.",
        "vendor": "LUXE Global",
        "category": "Apparel & Accessories > Clothing > Outerwear",
        "type": "Apparel",
        "tags": "Apparel, Wool, Heritage, Outerwear",
        "sku": "LXG-APP-002",
        "grams": 1400,
        "qty": 25,
        "price": 28000,
        "requires_shipping": "TRUE",
        "image": "photo-1550101361-43e550ffbf66",
        "alt": "Heritage wool jacket in Italian wool",
    },
    {
        "handle": "canvas-sneakers",
        "title": "Canvas Low Sneakers",
        "body_en": "Unwashed cotton canvas on a vulcanized rubber sole. Two stitched eyelets, cushioned insole, zero hardware.",
        "vendor": "LUXE Global",
        "category": "Apparel & Accessories > Shoes",
        "type": "Apparel",
        "tags": "Apparel, Footwear, Canvas, Sneakers",
        "sku": "LXG-APP-003",
        "grams": 700,
        "qty": 40,
        "price": 9800,
        "requires_shipping": "TRUE",
        "image": "photo-1759527588071-e143b4a451b0",
        "alt": "White canvas low sneakers minimalist",
    },
    {
        "handle": "oak-chair",
        "title": "Hand-Crafted Oak Chair",
        "body_en": "Solid white oak, mortise and tenon joinery, hand-finished with food-safe oil. Made one at a time in a small Hokkaido workshop.",
        "vendor": "LUXE Global",
        "category": "Furniture > Chairs",
        "type": "Home",
        "tags": "Home, Furniture, Oak, Handcrafted",
        "sku": "LXG-HOM-001",
        "grams": 6500,
        "qty": 8,
        "price": 38000,
        "requires_shipping": "TRUE",
        "image": "photo-1636216225378-4ab4ca54ea13",
        "alt": "Solid white oak hand-crafted chair",
    },
    {
        "handle": "ceramic-lamp",
        "title": "Ceramic Table Lamp",
        "body_en": "A round stoneware base in matte porcelain glaze, paired with an unbleached linen shade. Warm-white LED included.",
        "vendor": "LUXE Global",
        "category": "Furniture > Lamps & Lighting > Table Lamps",
        "type": "Home",
        "tags": "Home, Lighting, Ceramic, Lamp",
        "sku": "LXG-HOM-002",
        "grams": 2200,
        "qty": 18,
        "price": 12800,
        "requires_shipping": "TRUE",
        "image": "photo-1735807009262-59c7c0366042",
        "alt": "Ceramic table lamp with linen shade",
    },
    {
        "handle": "walnut-table",
        "title": "Walnut Coffee Table",
        "body_en": "American black walnut with bookmatched grain. Pinned breadboard ends, hand-rubbed oil finish, sealed against rings.",
        "vendor": "LUXE Global",
        "category": "Furniture > Tables > Coffee Tables",
        "type": "Home",
        "tags": "Home, Furniture, Walnut, Coffee Table",
        "sku": "LXG-HOM-003",
        "grams": 18000,
        "qty": 5,
        "price": 58000,
        "requires_shipping": "TRUE",
        "image": "photo-1766232590982-67ef5c70b787",
        "alt": "American walnut coffee table bookmatched",
    },
    {
        "handle": "ethiopia-coffee",
        "title": "Single Origin Ethiopia 200g",
        "body_en": "Yirgacheffe washed lot. Notes of jasmine, bergamot, and stone fruit. Roasted within seven days of shipping.",
        "vendor": "LUXE Global",
        "category": "Food, Beverages & Tobacco > Beverages > Coffee",
        "type": "Food",
        "tags": "Food, Coffee, Single Origin, Ethiopia",
        "sku": "LXG-FOO-001",
        "grams": 250,
        "qty": 100,
        "price": 1800,
        "requires_shipping": "TRUE",
        "image": "photo-1675306408031-a9aad9f23308",
        "alt": "Single origin Ethiopia coffee beans",
    },
    {
        "handle": "raw-honey",
        "title": "Raw Wildflower Honey",
        "body_en": "Unfiltered, unpasteurized, single-apiary honey from the foothills of Nagano. 280g jar with wooden dipper.",
        "vendor": "LUXE Global",
        "category": "Food, Beverages & Tobacco > Food Items > Condiments & Sauces > Honey",
        "type": "Food",
        "tags": "Food, Honey, Raw, Nagano",
        "sku": "LXG-FOO-002",
        "grams": 380,
        "qty": 80,
        "price": 2400,
        "requires_shipping": "TRUE",
        "image": "photo-1587049352851-8d4e89133924",
        "alt": "Raw wildflower honey jar with wooden dipper",
    },
    {
        "handle": "assam-tea",
        "title": "Premium Assam Tea",
        "body_en": "Second-flush Assam from a high-elevation tea garden. Bold, malty, and substantial — the British breakfast standard.",
        "vendor": "LUXE Global",
        "category": "Food, Beverages & Tobacco > Beverages > Tea & Infusions",
        "type": "Food",
        "tags": "Food, Tea, Assam, Loose Leaf",
        "sku": "LXG-FOO-003",
        "grams": 150,
        "qty": 120,
        "price": 1200,
        "requires_shipping": "TRUE",
        "image": "photo-1666113802599-e4c8b2b9c3a1",
        "alt": "Premium Assam loose leaf tea",
    },
    {
        "handle": "coffee-monthly",
        "title": "Monthly Coffee Subscription (Monthly Subscription)",
        "body_en": "Two 200g bags from rotating origins, delivered the second Tuesday of each month. Pause or cancel anytime.",
        "vendor": "LUXE Global",
        "category": "Food, Beverages & Tobacco > Beverages > Coffee",
        "type": "Subscription",
        "tags": "Subscription, Coffee, Monthly",
        "sku": "LXG-SUB-001",
        "grams": 450,
        "qty": 100,
        "price": 3200,
        "requires_shipping": "TRUE",
        "image": "photo-1605711599412-775918dbe770",
        "alt": "Monthly coffee subscription bag",
    },
    {
        "handle": "aroma-monthly",
        "title": "Monthly Aroma Box (Monthly Subscription)",
        "body_en": "Three 10ml essential oils curated by season, plus a printed scent guide. Sourced from family-run distilleries.",
        "vendor": "LUXE Global",
        "category": "Health & Beauty > Personal Care > Cosmetics > Aromatherapy",
        "type": "Subscription",
        "tags": "Subscription, Aromatherapy, Essential Oil, Monthly",
        "sku": "LXG-SUB-002",
        "grams": 250,
        "qty": 100,
        "price": 4800,
        "requires_shipping": "TRUE",
        "image": "photo-1515377905703-c4788e51af15",
        "alt": "Monthly essential oil aromatherapy box",
    },
    {
        "handle": "notebook-monthly",
        "title": "Artisan Notebook Monthly (Monthly Subscription)",
        "body_en": "One A5 thread-bound notebook each month, paired with a refill cartridge. Ten paper variations across the year.",
        "vendor": "LUXE Global",
        "category": "Office Supplies > Stationery > Notebooks & Notepads",
        "type": "Subscription",
        "tags": "Subscription, Stationery, Notebook, Monthly",
        "sku": "LXG-SUB-003",
        "grams": 350,
        "qty": 100,
        "price": 2400,
        "requires_shipping": "TRUE",
        "image": "photo-1677064061401-f77f966ff8a1",
        "alt": "Artisan thread-bound notebook monthly",
    },
]

HEADERS = [
    "Handle",
    "Title",
    "Body (HTML)",
    "Vendor",
    "Product Category",
    "Type",
    "Tags",
    "Published",
    "Option1 Name",
    "Option1 Value",
    "Variant SKU",
    "Variant Grams",
    "Variant Inventory Tracker",
    "Variant Inventory Qty",
    "Variant Inventory Policy",
    "Variant Fulfillment Service",
    "Variant Price",
    "Variant Compare At Price",
    "Variant Requires Shipping",
    "Variant Taxable",
    "Variant Barcode",
    "Image Src",
    "Image Position",
    "Image Alt Text",
    "Gift Card",
    "SEO Title",
    "SEO Description",
    "Status",
]


def build_row(p):
    body_html = f"<p>{p['body_en']}</p>"
    image_url = f"https://images.unsplash.com/{p['image']}{UNSPLASH_PARAMS}"
    seo_desc = p["body_en"][:160]
    return [
        p["handle"],
        p["title"],
        body_html,
        p["vendor"],
        p["category"],
        p["type"],
        p["tags"],
        "TRUE",
        "Title",
        "Default Title",
        p["sku"],
        str(p["grams"]),
        "shopify",
        str(p["qty"]),
        "deny",
        "manual",
        str(p["price"]),
        "",
        p["requires_shipping"],
        "TRUE",
        "",
        image_url,
        "1",
        p["alt"],
        "FALSE",
        p["title"],
        seo_desc,
        "active",
    ]


def main():
    out_path = "/Users/igiryo/dev/mer-prog/luxe-global/products/products.csv"
    with open(out_path, "w", encoding="utf-8-sig", newline="") as f:
        writer = csv.writer(f, quoting=csv.QUOTE_MINIMAL, lineterminator="\n")
        writer.writerow(HEADERS)
        for p in PRODUCTS:
            writer.writerow(build_row(p))
    print(f"Wrote {len(PRODUCTS)} products to {out_path}")


if __name__ == "__main__":
    main()
